export const cryptoData = [
  {
    id: "btc",
    name: "Bitcoin",
    symbol: "BTC",
    amount: 1,
    usdValue: 24284.57,
    eurValue: 25170.04,
    audValue: 24924.14,
    change: 3.3,
    trend: "up",
    icon: "/images/crypto/bitcoin.png",
  },
  {
    id: "ltc",
    name: "Litecoin",
    symbol: "LTC",
    amount: 1,
    usdValue: 2745.34,
    eurValue: 3739.87,
    audValue: 3152.0,
    change: 1.8,
    trend: "down",
    icon: "/images/crypto/litecoin.png",
  },
  {
    id: "eth",
    name: "Etherium",
    symbol: "ETH",
    amount: 1,
    usdValue: 12758.11,
    eurValue: 13388.52,
    audValue: 12995.48,
    change: 2.7,
    trend: "up",
    icon: "/images/crypto/ethereum.png",
  },
  {
    id: "zcs",
    name: "Zcash",
    symbol: "ZCS",
    amount: 1,
    usdValue: 1657.0,
    eurValue: 2215.05,
    audValue: 1856.12,
    change: 4.2,
    trend: "up",
    icon: "/images/crypto/zcash.png",
  },
  {
    id: "bet",
    name: "Beta",
    symbol: "BET",
    amount: 1,
    usdValue: 3533.27,
    eurValue: 4230.85,
    audValue: 3967.02,
    change: 0.2,
    trend: "up",
    icon: "/images/crypto/bet.png",
  },
  {
    id: "sol",
    name: "Solana",
    symbol: "SOL",
    amount: 1,
    usdValue: 180.59,
    eurValue: 210.24,
    audValue: 205.3,
    change: 2.7,
    trend: "down",
    icon: "/images/crypto/solana.png",
  },
]

export const accountsData = [
  {
    id: "jpmorgan",
    name: "JPMorgan Chase",
    balance: 384595.2,
    currency: "USD",
    icon: "/images/banks/jpmorgan.png",
  },
  {
    id: "hsbc",
    name: "HSBC",
    balance: 34874.15,
    currency: "GBR",
    icon: "/images/banks/hsbc.png",
  },
  {
    id: "creditsuisse",
    name: "Credit Suisse",
    balance: 236564.0,
    currency: "EUR",
    icon: "/images/banks/credit-suisse.png",
  },
  {
    id: "revolut",
    name: "Revolut",
    balance: 341522.0,
    currency: "EUR",
    icon: "/images/banks/revolut.png",
  },
  {
    id: "payoneer",
    name: "Payoneer",
    balance: 68495.05,
    currency: "USD",
    icon: "/images/banks/payoneer.png",
  },
  {
    id: "bankofamerica",
    name: "Bank of America",
    balance: 1958.0,
    currency: "USD",
    icon: "/images/banks/bank-of-america.png",
  },
  {
    id: "monzo",
    name: "Monzo",
    balance: 2845.2,
    currency: "USD",
    icon: "/images/banks/monzo.png",
  },
]
